### ISSUE TITLE
Unneccessary fix of thieving hotkey 

### ISSUE THREAD

**Issue by wuxiangjinxing** [anongit/DragonspearUI#8]
The thieving hotkey is unnecessarily fixed to be 'F' even if the permanent thief button is turned off.  What's worse, this hotkey setting conflicts with the AI hotkey from SCS.  

What about moving this setting into the if block?  For instance I guess you could change the code in content-bg2\UI.menu, line 11032 as the following:

		PermThief = Infinity_GetINIValue('Game Options','PermThief',0)
		if PermThief ~= 1 then
			PermThief = 0
			Infinity_SetINIValue('Game Options','PermThief',0)
                else
                        Infinity_SetINIValue('Keymap Action','Thieving',102) --fix the thieving hotkey only when the permanent thieving option is ON
		end

**Comment by anongit** [comment]
I think it would be better to provide a warning to the player asking to setup hotkey for thieving and then use whatever the key was assigned.
