### ISSUE TITLE
Unable to remove spells in BG2?

### ISSUE THREAD

**Issue by dive-bomber** [anongit/DragonspearUI#9]
Erasing spells from spellbook straight out doesn't do anything, asks me if I want to remove it, I click 'remove', spell is still there. I specifically checked in clean install, because I thought it might be related to SCS' Icewind Dale spells or something so I created new illusionist in ToB and no dice either. 

It's not a huge issue to me, because I can erase them with EEkeeper, but I'm reporting nonetheless.

**Comment by anongit** [comment]
Thanks, fixed in the dev branch.
